name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install textlint and rules
      run: make install-lint

    - name: run textlint
      run: make lint