name: Deploy web pages
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build the book
    - name: Download mdbook
      shell: bash
      run: |
        curl -O --location https://github.com/leanprover/mdBook/releases/download/v0.4.6/mdbook-linux.tar.gz
        tar xvf mdbook-linux.tar.gz

    - name: Run mdbook build
      shell: bash
      run: |
        ./mdbook-linux/mdbook build

    #- name: Deploy
    #  uses: JamesIves/github-pages-deploy-action@4
    #  with:
    #    branch: gh-pages
    #    folder: book