name: Deploy web pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build the book
    - name: Download mdbook
      shell: bash
      run: |
        curl -O --location https://github.com/leanprover/mdBook/releases/download/v0.4.6/mdbook-linux.tar.gz
        tar xvf mdbook-linux.tar.gz

    - name: Run mdbook build
      shell: bash
      run: |
        ./mdbook-linux/mdbook build

    # Deploy the book
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: book